FROM openjdk:8-jdk-alpine
WORKDIR /project
RUN apk update && \
    apk add --no-cache git bash
RUN git clone https://github.com/MartinAhrer/continuousdelivery.git ./
RUN ./gradlew assemble --no-daemon

LABEL maintainer='Martin Ahrer <this@martinahrer.at>'
RUN mkdir -p /opt/app
EXPOSE 8080
CMD java -jar /opt/app/app.jar
RUN cp /project/build/libs/continuousdelivery-0.1.jar /opt/app/app.jar && \
    rm -rf /project
